### ISSUE TITLE
我如果backbone替换成efficientNetV2-s后，还能用.yaml文件里面depth和width参数来控制网络模型的大小吗？

### ISSUE THREAD

**Issue by nortorious** [WangRongsheng/BestYOLO#4]
yolov5可以通过修改depth和width参数，从而实现 s m l x四个版本的变化，我想知道的是主干网替换efficientNetV2-s，是否还能这样做？

**Comment by WangRongsheng** [comment]
可以的。建议全部改为1.0即可。

**Comment by nortorious** [comment]
但是我如果还是想用yolov5s的话，是不是还是把depth和width参数分别改成0.33和0.50？

**Comment by WangRongsheng** [comment]
是
